export const links = [
  ['/', 'Home'],
  ['/rebreather', 'Rebreather'],
  ['/game-of-life-classic', 'Game of Life Classic'],
  ['/game-of-life', 'Game of Life Smooth'],
  ['/game-of-life-genes', 'Game of Life Genes'],
  ['/geometry-of-circles', 'Geometry of Circles'],
  ['/scratch-clock-linear', 'Scratch Clock Linear'],
  ['/scratch-clock-radial', 'Scratch Clock Radial'],
  // ['/scratch-clock-radial-alt', 'Scratch Clock Radial (Alt)'],
  ['/fractal-tree', 'Fractal Tree'],
  ['/koch-snowflake-fractal-1', 'Koch Snowflake 1'],
  ['/koch-snowflake-fractal-2', 'Koch Snowflake 2'],
  ['/koch-snowflake-fractal-3', 'Koch Snowflake 3'],
  ['/boxes-1', 'Boxes 1'],
  ['/boxes-2', 'Boxes 2'],
  ['/boxes-3', 'Boxes 3'],
  ['/d3-pack', 'D3 Pack'],
  ['/d3-pack-eyes', 'D3 Pack Eyes'],
  ['/d3-rounded-rects', 'D3 Rounded Rects'],
  ['/fractal-monkey', 'Fractal Monkey'],
  ['/recursive-graph', 'Recursive Graph'],
  ['/cat-sprite', 'Cat Sprite'],
  ['/hex', 'Hex'],
  ['/generated-sprites', 'Generated Sprites'],
  ['/generated-flowers', 'Generated Flowers'],
]
