// THIS FILE IS AUTOGENERATED. DO NOT EDIT
/* eslint-disable */
/* tslint:disable */
export const noop = () => {}
import * as globalMouseHandler from './globalMouseHandler'
export { globalMouseHandler }